version: 2.1

jobs:
  build:
    docker:
      - image: python:3.10
    steps:
      - checkout
      - run:
          name: Run Main1.py
          command: python Main1.py

  test:
    docker:
      - image: python:3.10
    steps:
      - checkout
      - run:
          name: Run Test.py
          command: python Test.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
